<html>
<head>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://bootswatch.com/3/darkly/bootstrap.min.css">

    <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <title>Ducky Script -> P4wnP1 (aloa)</title>
    
    <style>
        .boxsizingBorder {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
                    box-sizing: border-box;

            height: 30%;
            width: 100%;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">DS2PP</a>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="panel panel-primary">

            <div class="panel-heading">
                Input
            </div>
            
            <!-- Form -->
            <form method="post">
                <div class="form-group">
                    <textarea rows="4" cols="50" class="boxsizingBorder" name="input">{{ input }}</textarea>
                </div>

                <div class="form-group">
                    <label>Layout</label>
                    <select class="form-control" name="layout">
                        <option value="us">🇺🇸 US</option>
                        <option value="gb">🇬🇧 GB</option>
                        <option value="de">🇩🇪 DE</option>
                        <option value="br">🇧🇷 BR</option>
                        <option value="es">🇪🇸 ES</option>
                        <option value="fr">🇫🇷 FR</option>
                        <option value="it">🇮🇹 IT</option>
                        <option value="ru">🇷🇺 RU</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <!-- End Form -->
        </div>

    {{ if_output_convert }}
        <div class="panel panel-primary">

            <!-- Errors -->
            {{ if_error }}
                <div class="alert alert-danger">{{ error_msg }}</div>
            {{ end_if_error }}
            <!-- /Errors -->

            <div class="panel-heading">
                Output
            </div>
            
            <!-- Output -->
            <textarea rows="4" cols="50" class="boxsizingBorder" name="input">{{ output }}</textarea>
            <!-- /Output -->

            <div class="alert alert-info">Execution time: {{ execution_time }} ms</div>
        </div>
    {{ end_if_output_convert }}

    </div>

</body>

<footer class="page-footer font-small teal pt-4">
    <div class="footer-copyright text-center py-3">
        © 2019 <a href="https://hywse.eu">hyWse</a> | <a href="https://hywse.eu/imprint">Imprint</a> | <a href="https://github.com/hyWse/ds2pp">GitHub</a>
    </div>
</footer>

</html>